# Generated by Django 5.1.5 on 2025-04-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='face_encoding',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='feature_descriptor',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
