# Generated by Django 5.1.5 on 2025-04-06 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('useraccounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='distinguishing_features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distinguishing_feature_name', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_name', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='spoken_languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spoken_language_name', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='missing_person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp_name', models.CharField(max_length=25)),
                ('age_range', models.CharField(choices=[('infants', '0 - 1'), ('toddler', '2 - 3'), ('childhood', '4 - 12'), ('teenage', '13 - 19'), ('in thier 20s', '20 - 29'), ('in thier 30s', '30 - 39'), ('in thier 40s', '40 - 49'), ('Senior', '50 and above')], max_length=15)),
                ('height', models.FloatField()),
                ('body_build', models.CharField(choices=[('S', 'slender'), ('M', 'muscular'), ('A', 'average')], max_length=15)),
                ('skin_color', models.CharField(choices=[('D', 'dark'), ('C', 'chocolate'), ('L', 'lightskin'), ('W', 'white')], max_length=15)),
                ('other_descriptions', models.TextField(blank=True, null=True)),
                ('last_seen_location', models.CharField(max_length=40)),
                ('last_seen_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccounts.authority')),
            ],
        ),
        migrations.CreateModel(
            name='missing_person_distinguishing_features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distinguishing_features', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.distinguishing_features')),
                ('missing_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.missing_person')),
            ],
            options={
                'unique_together': {('missing_person', 'distinguishing_features')},
            },
        ),
        migrations.AddField(
            model_name='missing_person',
            name='distinguishing_features',
            field=models.ManyToManyField(through='persons.missing_person_distinguishing_features', to='persons.distinguishing_features'),
        ),
        migrations.AddField(
            model_name='missing_person',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persons.race'),
        ),
        migrations.CreateModel(
            name='missing_person_spoken_languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missing_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.missing_person')),
                ('spoken_languages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.spoken_languages')),
            ],
            options={
                'unique_together': {('missing_person', 'spoken_languages')},
            },
        ),
        migrations.AddField(
            model_name='missing_person',
            name='spoken_languages',
            field=models.ManyToManyField(through='persons.missing_person_spoken_languages', to='persons.spoken_languages'),
        ),
    ]
