# Generated by Django 5.1.5 on 2025-04-14 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missing_person',
            name='last_seen_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.county'),
        ),
    ]
