# Generated by Django 5.1.5 on 2025-04-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_alter_missing_person_last_seen_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missing_person',
            name='body_build',
            field=models.CharField(choices=[('Slender', 'slender'), ('Muscular', 'muscular'), ('Average', 'average')], max_length=15),
        ),
        migrations.AlterField(
            model_name='missing_person',
            name='skin_color',
            field=models.CharField(choices=[('Dark', 'dark'), ('Chocolate', 'chocolate'), ('Lightskin', 'lightskin'), ('White', 'white')], max_length=15),
        ),
    ]
