# Generated by Django 5.1.5 on 2025-04-23 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_alter_missing_person_body_build_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='missing_person',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missing_person',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='missingpersonOutCome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('alive', 'found alive'), ('deceased', 'found deceased'), ('still_missing', 'still missing')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('missingperson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='persons.missing_person')),
            ],
        ),
    ]
